# Generated by Django 2.2.11 on 2020-03-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ring', models.CharField(max_length=2)),
                ('age', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
